### ISSUE TITLE
Upgrading from 0.14.0 to 0.14.1 breaks compatibility with `wasm32-unknown-unknown` target

### ISSUE THREAD

**Issue by bnjbvr** [EmbarkStudios/puffin#118]
puffin 0.14.1 introduces a new required wasm import `env::now`, that's apparently imported by `instant`. I suspect this is coming from the js-sys ecosystem, or it might even be a WASI standard. There should be a way to opt out of this, so one can use `puffin` in `wasm32-unknown-unknown` environments too.

It seems that 0.14.0 didn't depend at all on `instant`, so making the dependency on `instant` optional + reuse whatever was used before to retrieve the time, should be sufficient to fix this.

**Comment by bnjbvr** [comment]
Also I realize that it might be nice to have tests for that compile target, that just uses simple scopes etc.

**Comment by TimonPost** [comment]
Likely due to this change: https://github.com/EmbarkStudios/puffin/pull/112/files#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87e
