### ISSUE TITLE
puffin_http don't serve when not setting in a variable

### ISSUE THREAD

**Issue by buxx** [EmbarkStudios/puffin#128]
**Describe the bug**

Start puffin_http don't serve when used in ggez game.

**To Reproduce**

**Cargo.toml**

```toml
[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
ggez = "0.8.1"
puffin_http = "0.11.1"
```

**src/main.rs**

```rust
use ggez::{
    event,
    graphics::{self, Color},
    Context, GameResult,
};

struct MainState {}

impl MainState {
    fn new() -> GameResult<MainState> {
        Ok(Self {})
    }
}

impl event::EventHandler<ggez::GameError> for MainState {
    fn update(&mut self, ctx: &mut Context) -> GameResult {
        Ok(())
    }

    fn draw(&mut self, ctx: &mut Context) -> GameResult {
        let mut canvas = graphics::Canvas::from_frame(ctx, Color::BLACK);
        canvas.finish(ctx)?;
        Ok(())
    }
}

pub fn main() -> GameResult {
    let server_addr = format!("0.0.0.0:{}", puffin_http::DEFAULT_PORT);
    puffin_http::Server::new(&server_addr).unwrap();

    let cb = ggez::ContextBuilder::new("x", "");
    let (ctx, events_loop) = cb.build()?;
    let state = MainState::new().unwrap();
    event::run(ctx, events_loop, state)
}
```

When run, nothing crash, but there is no puffin server running. It can be checked with `netstat -tupln | grep 8585` on linux.

**Expected behavior**

Puffin server should be started.

**Screenshots**

n/a

**Device:**
 - OS: Linux Ubuntu 22.04

**Comment by buxx** [comment]
Server is correctly listening if add a let behind `puffin_http::Server::new(&server_addr).unwrap()` : 

```rust
let _puffin_server = puffin_http::Server::new(&server_addr).unwrap();
```

**Comment by repi** [comment]
this is expected due to Rust drop rules but yeah can be confusing / cryptic.  

think we should add a `#[must_use]` to `Server::new` so you get a compiler warning about it if you don't use the created object @TimonPost

**Comment by buxx** [comment]
Okay ! Thank you for your works and this answer !

**Comment by Kerollmops** [comment]
The main issue is that [the README example](https://github.com/EmbarkStudios/puffin/blob/main/puffin_http/README.md) and therefore [the code example visible on crates.io](https://crates.io/crates/puffin_http) should be updated 😅
