### ISSUE TITLE
Export Puffin-Viewer reports from the measured program

### ISSUE THREAD

**Issue by Kerollmops** [EmbarkStudios/puffin#160]
**Is your feature request related to a problem?**
We use Puffin in Meilisearch to measure the indexing functions used and the time they take to process. It is fairly easy to see the blocking steps. We will release this profiling feature as part of the next v1.4. However, we would like to ease the report export. We currently need to ask our users to run the `puffin_viewer` program alongside their Meilisearch but it would be great to export a report from Meilisearch itself. 

**Describe the solution you'd like**
It would measure just after being started and after being closed. The report would be viewable from `puffin_viewer`. Every frame would be written to disk in the `puffin_viewer` format until the program is closed.

**Describe alternatives you've considered**
Maybe running the `puffin_viewer` library HTTP server directly from Meilisearch and making it export the report by itself?

**Comment by repi** [comment]
you are in luck :smiley: https://docs.rs/puffin/latest/puffin/struct.FrameView.html#method.save_to_writer 

we use this ourselves also from our app

**Comment by Kerollmops** [comment]
Thank you very much! I missed this function, and it works great 😄  I am just wondering how many frames it will write to disk, it seems like the frames are not removed after a call to `save_to_writer` 🤔

**Comment by repi** [comment]
think it saves all of the available frames
