### ISSUE TITLE
Simple example app for puffin-imgui?

### ISSUE THREAD

**Issue by dbr** [EmbarkStudios/puffin#17]
## Background

I have attempted to integrate `puffin` into an application, but I am struggling. The instructions in the README are a little sparse, so I had to guess a few parts:

1. Added `puffin` and `puffin-imgui` as dependencies
2. Before my main event loop, did this:
```
let mut pui = puffin_imgui::ProfilerUi::default();
puffin::set_scopes_on(true);
```
3. In some interesting functions, added `puffin::profile_function!();` in the first line and added `puffin::profile_scope_data!("thing", "example");` in interesting loops etc
4. Inside end of main loop I called `pui.window(ui);`

However this ends up with a window appearing, but only ever contains "No profiling data"

## My suggestions

1. It would be very useful to have a simple example of how to use this. Something only slightly more complex than https://github.com/imgui-rs/imgui-rs/blob/master/imgui-examples/examples/hello_world.rs showing how to correctly wire up everything

2. Minor thing: The example code in README has `:` instead of `;` at end of lines

3. Having the little crates.io badge in the `puffin-imgui` README would be helpful (I put in `puffin = "0.3"` in `Cargo.toml` and I incorrectly assumed `puffin-imgui` was version-locked to this)

Thanks!

**Comment by emilk** [comment]
Hi, thanks for your issue!

You are right; this crate isn't very well documented. I'll improve it shortly!

In the meantime: I think what you may be missing is a call to [`GlobalProfiler::new_frame`](https://docs.rs/puffin/0.3.1/puffin/struct.GlobalProfiler.html#method.new_frame):

``` rust
puffin::GlobalProfiler::lock().new_frame();
```

You should call this once per frame in your game loop.

**Comment by dbr** [comment]
Ahh, yes that sounds very much like what I was missing (I was wondering how the UI knows what represents one frame!)

Thanks!

**Comment by emilk** [comment]
I've improved the documentation somewhat in <https://github.com/EmbarkStudios/puffin/commit/c254a578ab1b438d203c692e64d0d6b8e6470f1f>. I also discovered that the crate [`profiling`](https://github.com/aclysma/profiling) has a working example for `puffin`: https://github.com/aclysma/profiling/blob/master/examples/puffin/puffin.rs
