### ISSUE TITLE
Upload new release to `crates.io`

### ISSUE THREAD

**Issue by v0x0g** [EmbarkStudios/puffin#221]
# Problem

(Please see linked issue in `egui_miniquad` for more context)

I want to release one of my projects on `crates.io`, which requires that all of my deps are _fully published to `crates.io` as well_. Currently, I need to use a version of `puffin` and `puffin_http` that is newer than the last release `0.19.0`, which I am doing so by adding a `[patch.crates-io]` section to my `Cargo.toml`. This is a problem, since `cargo publish` ignores that and then I get broken builds. (Note: removing the `[patch]` section just gives me different errors since `git` deps aren't allowed).

# Solution

I'd like to ask that a new release be uploaded, so that the fixes (which have already been merged into `puffin/main`) get published to `crates.io`, where I and others can use them in our own packages.

# Alternatives

As far as I can tell there aren't any: `crates.io` has a requirement that all other deps must be published, with no way around it.

# Additional context

- #212, #213 : Changes I'm referring to that I need
- <https://github.com/not-fl3/egui-miniquad/issues/70#issue-2382134380>: Issue I opened in `egui_miniquad` for the same reason of publishing my crate

**Comment by emilk** [comment]
Done!
