### ISSUE TITLE
Misc UI issues with puffin-imgui

### ISSUE THREAD

**Issue by dbr** [EmbarkStudios/puffin#24]
Excuse the giant list of things, didn't want to spam the issue tracker with separate items (but if that's preferred, let me know and I'll split this up!)

1. Very narrow items disappear from view when zooming out:
![disappering_blips](https://user-images.githubusercontent.com/509/120748475-30ada100-c546-11eb-9fd2-d84f322a560b.gif)

2. The click-to-zoom behavior triggers erroneously sometimes. Seems more common with small items under cursor

    e.g in the following, I am trying to click and drag side-to-side to pan, but instead it somewhat randomly zooms to fit the item under the mouse:
    ![click_zoom_glitch](https://user-images.githubusercontent.com/509/120748679-884c0c80-c546-11eb-8e2d-448f4d87ef2f.gif)

    Maybe just needs to trigger on mouse_released?

3. The default zoom speed is extremely low, at least with both and mouse and a Thinkpad trackpad

    Personally I found the old right-click based zoom worked well, as I could very quickly zoom in and out over large time intervals. Possibly the two could co-exist, unless there is plans to use right-mouse for something else?

    A larger problem is there appears to be no way to access (and thus customize) the `Options` struct - `ProfilerUi::default()` seems to be the only way to instantiate it

4. Minor thing, but the collapsible "Frames" window takes up quite a lot of vertical space. It's quite a few clicks to change between frames, and view the frame-graph as full height.

    Possibly the widget could be rearranged a little, something like:

        [Pause] [Show/hide history] [Pause/Resume] [Merge children with same ID] [Help]

        Recent:  | graph        |
                 |______________|

        Slowest: | graph       |
        (clear)  |_____________|

        Current frame: 3.2ms, 1 threads, 6 scopes, 0.3kB.

         _____________________________
        | flame graph                 |
        | ...                         |
        |_____________________________|

    Where "Help" would either show a modal or tooltip with the "Drag to pan. Scroll to zoom [...] etc".

    I think this would save about 4 or 5 lines worth of vertical height without impacting the functionality. More drastically, the recent history/slowest frames widgets could possibly be reduced in height, maybe even half the height, but that's a bit more subjective

5. The "minor ticks" are quite hard to see. They fade in while zooming, but can be very hard to read when zoomed to see two major ticks:

    ![image](https://user-images.githubusercontent.com/509/120751225-fe527280-c54a-11eb-8a4f-7e3a7257260a.png)

6. Some labels are invisible when switching to imgui "Light"

    E.g using the Imgui Demo "Tools > Style Editor" window and selecting "Light" from the first Colors dropdown)

    Everything else seems to look good regardless of the active style, just the labels (text and button labels) become ~impossible to read

7. In "live" mode, the graph time ticks flicker at the end of the graph:

    ![ticks_flickering](https://user-images.githubusercontent.com/509/120756656-df57de80-c552-11eb-8194-879b32f9dcd5.gif)

    I guess this is useful in that it clearly indicates where the end of the data is, but looks very jarring

**Device:**
 - OS: Linux
 - Version: `puffin-imgui 0.8.0`

**Comment by emilk** [comment]
This is good feedback, and I'm working on some of it now (finally)
