### ISSUE TITLE
On Windows, short_file_name does not trim the file name

### ISSUE THREAD

**Issue by CAD97** [EmbarkStudios/puffin#27]
**Describe the bug**

https://github.com/EmbarkStudios/puffin/blob/616f6ee4456689a28dea642bbd42f7f0787a3803/puffin/src/lib.rs#L568-L578

This trims the `file!()` path based on the `/` delimiters, but `file!()` uses `\` delimiters on Windows.

**To Reproduce**
1. Run an example on Windows (e.g. one of the `puffin_egui` examples).
2. Note that the reported `location`s of spans differ from the trimmed `location`s on platforms that use `/` as the canonical path separator.
3. Note that this is even more drastic when using a profiled dependency from crates-io (such as `puffin_egui` itself), as the `location` path is now absolute rather than relative.

**Expected behavior**
Path cleaning behavior should be identical on all platforms.

**Device:**
 - OS: Windows Native
 - Version 21H1 (OS Build 19043.1055)

**Comment by emilk** [comment]
Thanks for the report! This has now been fixed in puffin 0.6.0
