### ISSUE TITLE
Viewer window doesn't open on Windows

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/puffin#35]
When simply just starting Puffin viewer on Windows 10, no application window is displayed/visible. 

Doing the same on Mac OS works fine though.

**Comment by NiklasNummelin** [comment]
I tested in on my w10 machine and it works. Will update stuff to the latest to be sure.

**Comment by emilk** [comment]
To be clear, running `cargo run -p puffin_viewer` show nothing @repi ?

**Comment by repi** [comment]
indeed it doesn't. well it does show the icon for the app in my start bar (which is on the right side here): 

![image](https://user-images.githubusercontent.com/1262692/129533562-329bb19f-e497-4882-8652-2ea8611dba52.png)

and in the cmd it does say that it is trying to connected:

> 2021-08-16 10:22:57,952 INFO  [puffin_http::client] Connecting to 127.0.0.1:8585…
> 2021-08-16 10:22:57,954 INFO  [puffin_http::client] Connected to 127.0.0.1:8585

but no window itself, quite weird. Wonder if it is somehow placed outside my desktop

**Comment by emilk** [comment]
Does removing `C:\Users\YOUR_USER_NAME\AppData\Roaming\puffin-http-client-viewer` help you @repi ?

If so, could be the viewer is remembering the old location of the window, and that it messes up somehow there. I know this has caused problems on windows before.

**Comment by repi** [comment]
Hah yup that solved it, classic!

**Comment by emilk** [comment]
Work-around for similar problems in the future: https://github.com/emilk/egui/commit/07303681c603e30fadbd8e71fee5202705fb68e9
