### ISSUE TITLE
Help Request: Perf issue when using puffin

### ISSUE THREAD

**Issue by siedentop** [EmbarkStudios/puffin#46]
Thank you for this awesome project!

I am trying to do some tracing measurements for [binocle][1]. However, when I use tracing with puffin (+puffin_http + viewer), there is a significant slowdown and most scopes do not show.

I prepared a branch which you can run: https://github.com/siedentop/binocle/tree/feature/eframe

```bash 
cargo run --example create_test_file
cargo run --features trace -- binocle_test_file
```

Could you please help me and tell me what I might have done wrong?

I know that the `Binocle::draw` method is using most of the time. (And yes, some work should move to a different thread, but I'd like some measurements first.) However, it only gets called if there is a `RedrawRequest` event, so it doesn't show in the trace viewer. 

With `puffin::GlobalProfiler::lock().new_frame();` in the main loop: 
<img width="804" alt="Screen Shot 2021-11-10 at 5 08 57 PM" src="https://user-images.githubusercontent.com/284732/141218746-bd0f61d7-d9f3-4bad-92b5-18fd1e9508dd.png">

And now with `puffin::GlobalProfiler::lock().new_frame();` just inside the `if let Event::RedrawRequested(_) = event`: 

<img width="880" alt="Screen Shot 2021-11-10 at 5 13 38 PM" src="https://user-images.githubusercontent.com/284732/141219198-0720f692-9eeb-4c6a-b895-72c7f299565f.png">

Any ideas? Many thanks (also feel free to close, if this isn't the right venue).

**Comment by emilk** [comment]
If you call `puffin::GlobalProfiler::lock().new_frame();` right inside `event_loop.run` you will be calling it for every new event that is received, which will mean each event will be treated as a new "frame", which is likely not what you want.

Calling it on `RedrawRequested` seems far more sensible.

---

As noted in the readme, each puffin profile scope costs 100-200 ns, so creating one for each pixel is a bad idea. Puffin is meant for more coarse-grained profiling.

**Comment by siedentop** [comment]
Thank you @emilk! This fixes it.

Originally, I had a trace point inside `color_at_index` method, which was called for every pixel! But I didn't realize it.

Great framework, and I already found one more performance issue 😊
