### ISSUE TITLE
Make puffin_egui packing feature optional, for wasm

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [EmbarkStudios/puffin#50]
puffin_egui has a required dependency on puffin with the `packing` feature, which brings in `zstd`, which can't compile to the `wasm32-unknown-unknown` target (https://github.com/rustwasm/team/issues/291#issue-577973691).

Can puffin_egui be altered to have a feature gate for using the packing functionality, so that it can be disabled to work with a wasm target?

**Comment by emilk** [comment]
Good luck!

Note that if you are planning on running puffin in a browser, you only will get millisecond precision on the profiling events due to meltdown/specter mitigation.

**Comment by ColonelThirtyTwo** [comment]
Ah well, better than nothing. Thanks for making the change though!
