### ISSUE TITLE
Image license?

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/puffin#54]
@emilk do you know where you got the puffin picture in the README from? wikipedia or similar? was added in the [initial commit: https://github.com/EmbarkStudios/puffin/blob/main/puffin.jpg](https://github.com/EmbarkStudios/puffin/blob/main/puffin.jpg)

if we figure it out can update the README with a small line under it to credit the author and potentially specify the license of it.

**Comment by emilk** [comment]
There is a line about it under [the **license** header](https://github.com/EmbarkStudios/puffin/blob/main/README.md#license), but it would make sense to move it to be closer to the image

**Comment by repi** [comment]
ah great that we had one already!
