### ISSUE TITLE
Remove zstd dependency in favor of ruzstd all together

### ISSUE THREAD

**Issue by Jasper-Bekkers** [EmbarkStudios/puffin#68]
Right now it looks like ruzstd is used only in the wasm build. I'm not sure if that's because it's not fast enough for other cases, however, when it comes to build time, ruzstd is quite a bit nicer to have instead.

Another option would be to keep it an optional feature, but to expose it as well in the imgui and other subcrates.

**Comment by emilk** [comment]
`ruzstd` is used as a decoder on wasm, but `zstd` is used both for decoding and _encoding_. `ruzstd` does not have a compressor, so it cannot replace `zstd`.
