### ISSUE TITLE
Don't merge scopes that have non-matching dynamic data

### ISSUE THREAD

**Issue by hrydgard** [EmbarkStudios/puffin#73]
Scopes can have dynamic data, like this:

```rust
puffin::profile_scope!("my_scope_id", my_dynamic_data);
```

However, puffin's UI still happily merges blocks with different dynamic data together if merging is enabled. It would be nice with a mode that would only merge identical blocks if their dynamic data is also identical, not if it's different.

**Comment by repi** [comment]
ah yes! didn't know we had an issue on it, was just a 10 min fix. will mark it resolved by my PR
